#Config.HOST_NAME=10.163.31.20
#Config.PORT_NUMBER=1521
#Config.DATA_BASE_DRIVER=oracle.jdbc.OracleDriver
#Config.DSN=jdbc:oracle:thin:
#Config.SID=twaddb
#Config.USER_NAME=twadlive
#Config.PASSWORD=twadliveaeiou
#Config.DATABASE_TYPE=OracleLiteu
#Config.DATABASE_NAME=twad_data
#Config.EMPLOYEE_PHOTOS_PATH=/public_html/images/EmpPhotos/
#Config.EMPLOYEE_PHOTOS_PATH_VIEW=/images/EmpPhotos/
#Config.PDF_PATH_VIEW=/WEB-INF/News_Xml

#Config.HOST_NAME=172.168.1.66
#Config.PORT_NUMBER=5434
#Config.DATA_BASE_DRIVER=org.postgresql.Driver
#Config.DSN=jdbc:postgresql
#Config.SID=tn1
#Config.USER_NAME=postgres
#Config.PASSWORD=chris123
#Config.DATABASE_TYPE=OracleLiteu
#Config.DATABASE_NAME=tn1

#--test_db_22_jan_25--
#Config.HOST_NAME=172.168.0.88
#Config.PORT_NUMBER=5434
#Config.DATA_BASE_DRIVER=org.postgresql.Driver
#Config.DSN=jdbc:postgresql
#Config.SID=test_dec_9
#Config.USER_NAME=postgres
#Config.PASSWORD=Tw@DP0stGreSQl@2O24
#Config.DATABASE_TYPE=OracleLiteu 
#Config.DATABASE_NAME=test_dec_9

#----------------------------------------------------------------------PRODUCTION DB----R-------------------------------------------------------------------------------------

#TWAD_NEST_PROD [PRODUCTION]
Config.HOST_NAME=172.168.0.88
Config.PORT_NUMBER=5434
Config.DATA_BASE_DRIVER=org.postgresql.Driver
Config.DSN=jdbc:postgresql
Config.SID=twad_nest_prod
#Config.SID=testdb_march13_2026
Config.USER_NAME=postgres
Config.PASSWORD=Tw@DP0stGreSQl@2O24
Config.DATABASE_TYPE=OracleLiteu 
Config.DATABASE_NAME=twad_nest_prod
#Config.DATABASE_NAME=testdb_march13_2026


#-----------------------------------------------------------------------JUNE TEST DB------------------------------------------------------------------------------------
##testdb_09_06_2025
#Config.HOST_NAME=172.168.0.88
#Config.PORT_NUMBER=5434
#Config.DATA_BASE_DRIVER=org.postgresql.Driver
#Config.DSN=jdbc:postgresql
#Config.SID=testdb_09_06_2025
#Config.USER_NAME=postgres
#Config.PASSWORD=Tw@DP0stGreSQl@2O24
#Config.DATABASE_TYPE=OracleLiteu
#Config.DATABASE_NAME=testdb_09_06_2025
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#test
#Config.HOST_NAME=172.168.0.88
#Config.PORT_NUMBER=5434
#Config.DATA_BASE_DRIVER=org.postgresql.Driver
#Config.DSN=jdbc:postgresql
#Config.SID=twad - 4-july
#Config.USER_NAME=postgres
#Config.PASSWORD=Tw@DP0stGreSQl@2O24
#Config.DATABASE_TYPE=OracleLiteu 
#Config.DATABASE_NAME=twad - 4-july




#Config.HOST_NAME=172.168.0.40
#Config.PORT_NUMBER=5436
#Config.DATA_BASE_DRIVER=org.postgresql.Driver
#Config.DSN=jdbc:postgresql
#Config.SID=twad_demo
#Config.USER_NAME=postgres
#Config.PASSWORD=postgres12345
#Config.DATABASE_TYPE=OracleLiteu 
#Config.DATABASE_NAME=twad_demo


#Config.HOST_NAME=172.168.0.88
#Config.PORT_NUMBER=5432
#Config.DATA_BASE_DRIVER=org.postgresql.Driver
#Config.DSN=jdbc:postgresql
#Config.SID=tn4 
#Config.USER_NAME=postgres
#Config.PASSWORD=postgres123
#Config.DATABASE_TYPE=OracleLiteu 
#Config.DATABASE_NAME=tn4

#Config.HOST_NAME=10.163.14.135
#Config.PORT_NUMBER=1521
#Config.DATA_BASE_DRIVER=oracle.jdbc.OracleDriver
#Config.DSN=jdbc:oracle:thin:
#Config.SID=stpidb
#Config.USER_NAME=twadlivemay
#Config.PASSWORD=twadlivemay123 
#Config.DATABASE_TYPE=OracleLiteu
#Config.DATABASE_NAME=twad_data
#Config.EMPLOYEE_PHOTOS_PATH=/public_html/images/EmpPhotos/
#Config.EMPLOYEE_PHOTOS_PATH_VIEW=/images/EmpPhotos/
#Config.PDF_PATH_VIEW=/WEB-INF/News_Xml


#-twad-nest-prod-
#Config.HOST_NAME=172.168.0.88
#Config.PORT_NUMBER=5432
#Config.DATA_BASE_DRIVER=org.postgresql.Driver
#Config.DSN=jdbc:postgresql
#Config.SID=tn4 
#Config.USER_NAME=postgres
#Config.PASSWORD=postgres123
#Config.DATABASE_TYPE=OracleLiteu 
#Config.DATABASE_NAME=tn4