/*
 * Generated by JasperReports - 23/12/20 6:14 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class NewGPF_Abstract_Headoffice_sjv_1608727477627_206133 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_month_value = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_cb_year = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_t_yr = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_officeid = null;
    private JRFillParameter parameter_sup_no = null;
    private JRFillParameter parameter_sql2 = null;
    private JRFillParameter parameter_Section = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_cb_mon = null;
    private JRFillParameter parameter_sql1 = null;
    private JRFillParameter parameter_f_yr = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_CURR_NET = null;
    private JRFillField field_TOT_MON_CR_UPTO = null;
    private JRFillField field_MON_UPTO_DISP = null;
    private JRFillField field_TOTAL_DR = null;
    private JRFillField field_PRTGRP = null;
    private JRFillField field_MON_UPTO = null;
    private JRFillField field_TOTAL_CR = null;
    private JRFillField field_YEAR_ACCOUNT_HEAD_CODE = null;
    private JRFillField field_TOT_MON_DR_UPTO = null;
    private JRFillField field_YEAR_NET_DISP = null;
    private JRFillField field_YEAR_NET = null;
    private JRFillField field_YEAR_NET_DISPLAY = null;
    private JRFillField field_YEAR_CR_SJV = null;
    private JRFillField field_ACCOUNT_HEAD_DES = null;
    private JRFillField field_YEAR_DR_SJV = null;
    private JRFillField field_MONTH_CLOSURE_STAT = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_SUM_CURRENT_MONTH_DEBIT_1 = null;
    private JRFillVariable variable_SUM_CURRENT_MONTH_CREDIT_1 = null;
    private JRFillVariable variable_SUM_YEAR_DR_1 = null;
    private JRFillVariable variable_SUM_YEAR_CR_1 = null;
    private JRFillVariable variable_SUM_CURR_NET_1 = null;
    private JRFillVariable variable_SUM_YEAR_NET_1 = null;
    private JRFillVariable variable_SUM_MON40DR41_UPTO = null;
    private JRFillVariable variable_SUM_MON40CR41_UPTO = null;
    private JRFillVariable variable_MonthandYear = null;
    private JRFillVariable variable_SUM_YR_NET_1 = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_month_value = (JRFillParameter)pm.get("month_value");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_cb_year = (JRFillParameter)pm.get("cb_year");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_t_yr = (JRFillParameter)pm.get("t_yr");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_officeid = (JRFillParameter)pm.get("officeid");
        parameter_sup_no = (JRFillParameter)pm.get("sup_no");
        parameter_sql2 = (JRFillParameter)pm.get("sql2");
        parameter_Section = (JRFillParameter)pm.get("Section");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_cb_mon = (JRFillParameter)pm.get("cb_mon");
        parameter_sql1 = (JRFillParameter)pm.get("sql1");
        parameter_f_yr = (JRFillParameter)pm.get("f_yr");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_CURR_NET = (JRFillField)fm.get("CURR_NET");
        field_TOT_MON_CR_UPTO = (JRFillField)fm.get("TOT_MON_CR_UPTO");
        field_MON_UPTO_DISP = (JRFillField)fm.get("MON_UPTO_DISP");
        field_TOTAL_DR = (JRFillField)fm.get("TOTAL_DR");
        field_PRTGRP = (JRFillField)fm.get("PRTGRP");
        field_MON_UPTO = (JRFillField)fm.get("MON_UPTO");
        field_TOTAL_CR = (JRFillField)fm.get("TOTAL_CR");
        field_YEAR_ACCOUNT_HEAD_CODE = (JRFillField)fm.get("YEAR_ACCOUNT_HEAD_CODE");
        field_TOT_MON_DR_UPTO = (JRFillField)fm.get("TOT_MON_DR_UPTO");
        field_YEAR_NET_DISP = (JRFillField)fm.get("YEAR_NET_DISP");
        field_YEAR_NET = (JRFillField)fm.get("YEAR_NET");
        field_YEAR_NET_DISPLAY = (JRFillField)fm.get("YEAR_NET_DISPLAY");
        field_YEAR_CR_SJV = (JRFillField)fm.get("YEAR_CR_SJV");
        field_ACCOUNT_HEAD_DES = (JRFillField)fm.get("ACCOUNT_HEAD_DES");
        field_YEAR_DR_SJV = (JRFillField)fm.get("YEAR_DR_SJV");
        field_MONTH_CLOSURE_STAT = (JRFillField)fm.get("MONTH_CLOSURE_STAT");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_SUM_CURRENT_MONTH_DEBIT_1 = (JRFillVariable)vm.get("SUM_CURRENT_MONTH_DEBIT_1");
        variable_SUM_CURRENT_MONTH_CREDIT_1 = (JRFillVariable)vm.get("SUM_CURRENT_MONTH_CREDIT_1");
        variable_SUM_YEAR_DR_1 = (JRFillVariable)vm.get("SUM_YEAR_DR_1");
        variable_SUM_YEAR_CR_1 = (JRFillVariable)vm.get("SUM_YEAR_CR_1");
        variable_SUM_CURR_NET_1 = (JRFillVariable)vm.get("SUM_CURR_NET_1");
        variable_SUM_YEAR_NET_1 = (JRFillVariable)vm.get("SUM_YEAR_NET_1");
        variable_SUM_MON40DR41_UPTO = (JRFillVariable)vm.get("SUM_MON(DR)_UPTO");
        variable_SUM_MON40CR41_UPTO = (JRFillVariable)vm.get("SUM_MON(CR)_UPTO");
        variable_MonthandYear = (JRFillVariable)vm.get("MonthandYear");
        variable_SUM_YR_NET_1 = (JRFillVariable)vm.get("SUM_YR_NET_1");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_DR_SJV.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_CR_SJV.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_DR.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_CR.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CURR_NET.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MON_UPTO.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MON_DR_UPTO.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MON_CR_UPTO.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.lang.String)field_YEAR_NET_DISP.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_month_value.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_cb_year.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_cb_year.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_month_value.getValue())+"-");//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_sup_no.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_sup_no.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_ACCOUNT_HEAD_CODE.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ACCOUNT_HEAD_DES.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PRTGRP.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_DR_SJV.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_CR_SJV.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_YEAR_NET_DISP.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_SUM_CURRENT_MONTH_DEBIT_1.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_SUM_CURRENT_MONTH_CREDIT_1.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_SUM_YR_NET_1.getValue()).intValue() < 0 ? ((java.math.BigDecimal)variable_SUM_YR_NET_1.getValue()).intValue() * -1 + " Dr " : ((java.math.BigDecimal)variable_SUM_YR_NET_1.getValue()).intValue()+" Cr ");//$JR_EXPR_ID=32$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_DR_SJV.getOldValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_CR_SJV.getOldValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_DR.getOldValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_CR.getOldValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CURR_NET.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MON_UPTO.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MON_DR_UPTO.getOldValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MON_CR_UPTO.getOldValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.lang.String)field_YEAR_NET_DISP.getOldValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_month_value.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_cb_year.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_cb_year.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_month_value.getValue())+"-");//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_sup_no.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_sup_no.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_ACCOUNT_HEAD_CODE.getOldValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ACCOUNT_HEAD_DES.getOldValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PRTGRP.getOldValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_DR_SJV.getOldValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_CR_SJV.getOldValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_YEAR_NET_DISP.getOldValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_SUM_CURRENT_MONTH_DEBIT_1.getOldValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_SUM_CURRENT_MONTH_CREDIT_1.getOldValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_SUM_YR_NET_1.getOldValue()).intValue() < 0 ? ((java.math.BigDecimal)variable_SUM_YR_NET_1.getOldValue()).intValue() * -1 + " Dr " : ((java.math.BigDecimal)variable_SUM_YR_NET_1.getOldValue()).intValue()+" Cr ");//$JR_EXPR_ID=32$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_DR_SJV.getValue()));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_CR_SJV.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_DR.getValue()));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOTAL_CR.getValue()));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CURR_NET.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MON_UPTO.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MON_DR_UPTO.getValue()));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_TOT_MON_CR_UPTO.getValue()));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(((java.lang.String)field_YEAR_NET_DISP.getValue()));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_month_value.getValue()));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_cb_year.getValue()));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_cb_year.getValue()));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_month_value.getValue())+"-");//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_sup_no.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.Integer)(((java.lang.Integer)parameter_sup_no.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_ACCOUNT_HEAD_CODE.getValue()));//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.String)(((java.lang.String)field_ACCOUNT_HEAD_DES.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.String)(((java.lang.String)field_PRTGRP.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_DR_SJV.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_YEAR_CR_SJV.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.lang.String)(((java.lang.String)field_YEAR_NET_DISP.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_SUM_CURRENT_MONTH_DEBIT_1.getEstimatedValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_SUM_CURRENT_MONTH_CREDIT_1.getEstimatedValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_SUM_YR_NET_1.getEstimatedValue()).intValue() < 0 ? ((java.math.BigDecimal)variable_SUM_YR_NET_1.getEstimatedValue()).intValue() * -1 + " Dr " : ((java.math.BigDecimal)variable_SUM_YR_NET_1.getEstimatedValue()).intValue()+" Cr ");//$JR_EXPR_ID=32$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
