/*
 * Generated by JasperReports - 8/28/23 2:26 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class cash_book_ACCDetails_1693212984173_982366 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_PassBook_CB = null;
    private JRFillParameter parameter_txtAcc_No = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_SUBREPORT_DIR = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_accountingunit_name = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_monthInWords = null;
    private JRFillParameter parameter_txtCB_Month = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_txtCB_Year = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_bankOpeningBal_for_OPR = null;
    private JRFillParameter parameter_acpara = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_bankOpeningBal_for_COL = null;
    private JRFillParameter parameter_PassBook_OB = null;
    private JRFillParameter parameter_accountingunitid = null;
    private JRFillField field_voudate = null;
    private JRFillField field_office_name = null;
    private JRFillField field_Recamt = null;
    private JRFillField field_Payamt = null;
    private JRFillField field_bank_name = null;
    private JRFillField field_bid = null;
    private JRFillField field_acno = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_Rec_Amt_Sum = null;
    private JRFillVariable variable_Pay_Amt_Sum = null;
    private JRFillVariable variable_Total_Abstract = null;
    private JRFillVariable variable_CB_Abstract = null;
    private JRFillVariable variable_closing_bal_COL = null;
    private JRFillVariable variable_closing_bal_OPR = null;
    private JRFillVariable variable_tot_Recamt = null;
    private JRFillVariable variable_tot_Payamt = null;
    private JRFillVariable variable_new = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_PassBook_CB = (JRFillParameter)pm.get("PassBook_CB");
        parameter_txtAcc_No = (JRFillParameter)pm.get("txtAcc_No");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_SUBREPORT_DIR = (JRFillParameter)pm.get("SUBREPORT_DIR");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_accountingunit_name = (JRFillParameter)pm.get("accountingunit_name");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_monthInWords = (JRFillParameter)pm.get("monthInWords");
        parameter_txtCB_Month = (JRFillParameter)pm.get("txtCB_Month");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_txtCB_Year = (JRFillParameter)pm.get("txtCB_Year");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_bankOpeningBal_for_OPR = (JRFillParameter)pm.get("bankOpeningBal_for_OPR");
        parameter_acpara = (JRFillParameter)pm.get("acpara");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_bankOpeningBal_for_COL = (JRFillParameter)pm.get("bankOpeningBal_for_COL");
        parameter_PassBook_OB = (JRFillParameter)pm.get("PassBook_OB");
        parameter_accountingunitid = (JRFillParameter)pm.get("accountingunitid");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_voudate = (JRFillField)fm.get("voudate");
        field_office_name = (JRFillField)fm.get("office_name");
        field_Recamt = (JRFillField)fm.get("Recamt");
        field_Payamt = (JRFillField)fm.get("Payamt");
        field_bank_name = (JRFillField)fm.get("bank_name");
        field_bid = (JRFillField)fm.get("bid");
        field_acno = (JRFillField)fm.get("acno");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_Rec_Amt_Sum = (JRFillVariable)vm.get("Rec_Amt_Sum");
        variable_Pay_Amt_Sum = (JRFillVariable)vm.get("Pay_Amt_Sum");
        variable_Total_Abstract = (JRFillVariable)vm.get("Total_Abstract");
        variable_CB_Abstract = (JRFillVariable)vm.get("CB_Abstract");
        variable_closing_bal_COL = (JRFillVariable)vm.get("closing_bal_COL");
        variable_closing_bal_OPR = (JRFillVariable)vm.get("closing_bal_OPR");
        variable_tot_Recamt = (JRFillVariable)vm.get("tot_Recamt");
        variable_tot_Payamt = (JRFillVariable)vm.get("tot_Payamt");
        variable_new = (JRFillVariable)vm.get("new");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Recamt.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Payamt.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()).doubleValue())+(((java.math.BigDecimal)variable_Rec_Amt_Sum.getValue()).doubleValue())));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Total_Abstract.getValue()).doubleValue())-(((java.math.BigDecimal)variable_Pay_Amt_Sum.getValue()).doubleValue())));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Rec_Amt_Sum.getValue()).doubleValue()) +( ((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()).doubleValue())));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Pay_Amt_Sum.getValue()).doubleValue()) -( ((java.lang.Double)parameter_bankOpeningBal_for_OPR.getValue()).doubleValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Payamt.getValue())!=null?((java.math.BigDecimal)variable_tot_Payamt.getValue()):(new BigDecimal(0.00)));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_bank_name.getValue())+" - "+((java.math.BigDecimal)field_acno.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_office_name.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)("CASH BOOK FOR THE MONTH OF"+((java.lang.String)parameter_monthInWords.getValue())+" - "+((java.lang.Integer)parameter_txtCB_Year.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)("Accounting Unit Name: "+((java.lang.String)parameter_accountingunit_name.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_PassBook_OB.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_PassBook_CB.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_voudate.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_voudate.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_txtAcc_No.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_txtCB_Month.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.sql.Date)field_voudate.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_txtCB_Year.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_accountingunitid.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) +"cash_book_ACCDetails_subreport0.jasper");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_txtAcc_No.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.sql.Date)field_voudate.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_accountingunitid.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue())+"cash_book_ACCDetails_subreport_pay.jasper");//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Rec_Amt_Sum.getValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Pay_Amt_Sum.getValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Total_Abstract.getValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CB_Abstract.getValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Recamt.getValue())!=null?((java.math.BigDecimal)variable_tot_Recamt.getValue()):(new BigDecimal(0)));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_tot_Recamt.getValue()).subtract( ((java.math.BigDecimal)variable_Rec_Amt_Sum.getValue()) ).equals(new BigDecimal(0))?"Receipt Amount Tallied":"Receipt Amount not Tallied");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Payamt.getValue())!=null?((java.math.BigDecimal)variable_tot_Payamt.getValue()):(new BigDecimal(0.00)));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_new.getValue()).subtract( ((java.math.BigDecimal)variable_Pay_Amt_Sum.getValue()) ).equals(new BigDecimal(0))?"Payment Amount Tallied":"Payment Amount not Tallied");//$JR_EXPR_ID=50$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Recamt.getOldValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Payamt.getOldValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()).doubleValue())+(((java.math.BigDecimal)variable_Rec_Amt_Sum.getOldValue()).doubleValue())));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Total_Abstract.getOldValue()).doubleValue())-(((java.math.BigDecimal)variable_Pay_Amt_Sum.getOldValue()).doubleValue())));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Rec_Amt_Sum.getOldValue()).doubleValue()) +( ((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()).doubleValue())));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Pay_Amt_Sum.getOldValue()).doubleValue()) -( ((java.lang.Double)parameter_bankOpeningBal_for_OPR.getValue()).doubleValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Payamt.getOldValue())!=null?((java.math.BigDecimal)variable_tot_Payamt.getOldValue()):(new BigDecimal(0.00)));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_bank_name.getOldValue())+" - "+((java.math.BigDecimal)field_acno.getOldValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_office_name.getOldValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)("CASH BOOK FOR THE MONTH OF"+((java.lang.String)parameter_monthInWords.getValue())+" - "+((java.lang.Integer)parameter_txtCB_Year.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)("Accounting Unit Name: "+((java.lang.String)parameter_accountingunit_name.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_PassBook_OB.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_PassBook_CB.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_voudate.getOldValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_voudate.getOldValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_txtAcc_No.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_txtCB_Month.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.sql.Date)field_voudate.getOldValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_txtCB_Year.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_accountingunitid.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) +"cash_book_ACCDetails_subreport0.jasper");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_txtAcc_No.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.sql.Date)field_voudate.getOldValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_accountingunitid.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue())+"cash_book_ACCDetails_subreport_pay.jasper");//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Rec_Amt_Sum.getOldValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Pay_Amt_Sum.getOldValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Total_Abstract.getOldValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CB_Abstract.getOldValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Recamt.getOldValue())!=null?((java.math.BigDecimal)variable_tot_Recamt.getOldValue()):(new BigDecimal(0)));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_tot_Recamt.getOldValue()).subtract( ((java.math.BigDecimal)variable_Rec_Amt_Sum.getOldValue()) ).equals(new BigDecimal(0))?"Receipt Amount Tallied":"Receipt Amount not Tallied");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Payamt.getOldValue())!=null?((java.math.BigDecimal)variable_tot_Payamt.getOldValue()):(new BigDecimal(0.00)));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_new.getOldValue()).subtract( ((java.math.BigDecimal)variable_Pay_Amt_Sum.getOldValue()) ).equals(new BigDecimal(0))?"Payment Amount Tallied":"Payment Amount not Tallied");//$JR_EXPR_ID=50$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Double)(new Double(0));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Recamt.getValue()));//$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Payamt.getValue()));//$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()).doubleValue())+(((java.math.BigDecimal)variable_Rec_Amt_Sum.getEstimatedValue()).doubleValue())));//$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Total_Abstract.getEstimatedValue()).doubleValue())-(((java.math.BigDecimal)variable_Pay_Amt_Sum.getEstimatedValue()).doubleValue())));//$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Rec_Amt_Sum.getEstimatedValue()).doubleValue()) +( ((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()).doubleValue())));//$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal((((java.math.BigDecimal)variable_Pay_Amt_Sum.getEstimatedValue()).doubleValue()) -( ((java.lang.Double)parameter_bankOpeningBal_for_OPR.getValue()).doubleValue())));//$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = (java.math.BigDecimal)(new BigDecimal(0.0));//$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Payamt.getEstimatedValue())!=null?((java.math.BigDecimal)variable_tot_Payamt.getEstimatedValue()):(new BigDecimal(0.00)));//$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = (java.lang.String)(((java.lang.String)field_bank_name.getValue())+" - "+((java.math.BigDecimal)field_acno.getValue()));//$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = (java.lang.String)(((java.lang.String)field_office_name.getValue()));//$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = (java.lang.String)("CASH BOOK FOR THE MONTH OF"+((java.lang.String)parameter_monthInWords.getValue())+" - "+((java.lang.Integer)parameter_txtCB_Year.getValue()));//$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = (java.lang.String)("Accounting Unit Name: "+((java.lang.String)parameter_accountingunit_name.getValue()));//$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = (java.util.Date)(new java.util.Date());//$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()));//$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_PassBook_OB.getValue()));//$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_PassBook_CB.getValue()));//$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_voudate.getValue()));//$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = (java.util.Date)(((java.sql.Date)field_voudate.getValue()));//$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_txtAcc_No.getValue()));//$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_txtCB_Month.getValue()));//$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = (java.lang.Object)(((java.sql.Date)field_voudate.getValue()));//$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_txtCB_Year.getValue()));//$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_accountingunitid.getValue()));//$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue()) +"cash_book_ACCDetails_subreport0.jasper");//$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = (java.lang.Object)(((java.lang.Long)parameter_txtAcc_No.getValue()));//$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = (java.lang.Object)(((java.sql.Date)field_voudate.getValue()));//$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = (java.lang.Object)(((java.lang.Integer)parameter_accountingunitid.getValue()));//$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = (java.sql.Connection)(((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()));//$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_SUBREPORT_DIR.getValue())+"cash_book_ACCDetails_subreport_pay.jasper");//$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = (java.lang.Double)(((java.lang.Double)parameter_bankOpeningBal_for_COL.getValue()));//$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Rec_Amt_Sum.getEstimatedValue()));//$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Pay_Amt_Sum.getEstimatedValue()));//$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Total_Abstract.getEstimatedValue()));//$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CB_Abstract.getEstimatedValue()));//$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Recamt.getEstimatedValue())!=null?((java.math.BigDecimal)variable_tot_Recamt.getEstimatedValue()):(new BigDecimal(0)));//$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_tot_Recamt.getEstimatedValue()).subtract( ((java.math.BigDecimal)variable_Rec_Amt_Sum.getEstimatedValue()) ).equals(new BigDecimal(0))?"Receipt Amount Tallied":"Receipt Amount not Tallied");//$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_tot_Payamt.getEstimatedValue())!=null?((java.math.BigDecimal)variable_tot_Payamt.getEstimatedValue()):(new BigDecimal(0.00)));//$JR_EXPR_ID=49$
                break;
            }
            case 50 : 
            {
                value = (java.lang.String)(((java.math.BigDecimal)variable_new.getEstimatedValue()).subtract( ((java.math.BigDecimal)variable_Pay_Amt_Sum.getEstimatedValue()) ).equals(new BigDecimal(0))?"Payment Amount Tallied":"Payment Amount not Tallied");//$JR_EXPR_ID=50$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
